// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUl5BIkOukQQowgOYmc5QgZq-MwW6LLZY',
    appId: '1:853401075169:web:639d871da2e7c155a5e6a0',
    messagingSenderId: '853401075169',
    projectId: 'lunotebook',
    authDomain: 'lunotebook.firebaseapp.com',
    storageBucket: 'lunotebook.firebasestorage.app',
    measurementId: 'G-381RPRYZ5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA36StqY9eNmNK-a72pzxzkAaE7jKYp-ao',
    appId: '1:853401075169:android:6226235d0f3184a8a5e6a0',
    messagingSenderId: '853401075169',
    projectId: 'lunotebook',
    storageBucket: 'lunotebook.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDglK1hXv7k2ZLwHT02ts_EyVwzX5ciQys',
    appId: '1:853401075169:ios:b02a52b4b4f4ff23a5e6a0',
    messagingSenderId: '853401075169',
    projectId: 'lunotebook',
    storageBucket: 'lunotebook.firebasestorage.app',
    iosBundleId: 'com.example.lunotebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDglK1hXv7k2ZLwHT02ts_EyVwzX5ciQys',
    appId: '1:853401075169:ios:b02a52b4b4f4ff23a5e6a0',
    messagingSenderId: '853401075169',
    projectId: 'lunotebook',
    storageBucket: 'lunotebook.firebasestorage.app',
    iosBundleId: 'com.example.lunotebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUl5BIkOukQQowgOYmc5QgZq-MwW6LLZY',
    appId: '1:853401075169:web:fb5f0191e1f26cb3a5e6a0',
    messagingSenderId: '853401075169',
    projectId: 'lunotebook',
    authDomain: 'lunotebook.firebaseapp.com',
    storageBucket: 'lunotebook.firebasestorage.app',
    measurementId: 'G-BEQPBT42JH',
  );
}
